aamfsd:
  left_front_shock_controller:
#    type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: left_front_shock
    pid: {p: 500.0, i: 10.0, d: 100.0}
  
  left_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: left_steering_joint
    pid: {p: 500.0, i: 10.0, d: 100.0}
    
  #traction
  left_front_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: left_front_axle
    pid: {p: 1500.0, i: 100.0, d: 750.0}
     
  right_front_shock_controller:
    type: effort_controllers/JointEffortController
    joint: right_front_shock
    pid: {p: 500.0, i: 10.0, d: 500.0}

  right_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: right_steering_joint
    pid: {p: 500.0, i: 10.0, d: 100.0}
    
  #traction
  right_front_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: right_front_axle
    pid: {p: 1500.0, i: 100.0, d: 750.0}

  left_rear_shock_controller:
    type: effort_controllers/JointEffortController
    joint: left_rear_shock
    pid: {p: 500.0, i: 10.0, d: 100.0}

  # traction
  left_rear_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: left_rear_axle
    pid: {p: 1500.0, i: 100.0, d: 750.0}
    
  right_rear_shock_controller:
    type: effort_controllers/JointEffortController
    joint: right_rear_shock
    pid: {p: 500.0, i: 10.0, d: 100.0}

  # traction
  right_rear_axle_controller:
#    type: effort_controllers/JointEffortController
    type: velocity_controllers/JointVelocityController
    joint: right_rear_axle
    pid: {p: 1500.0, i: 100.0, d: 750.0}
        
  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
ackerbot_joint_publisher:

    type: joint_state_controller/JointStateController
    publish_rate: 100
    extra_joints:
      - name: rear_left_wheel_spinning_joint
      - name: rear_right_wheel_spinning_joint

ackerbot_controller:

    type: ackerbot_controllers/AckermannController
    spinning_joints: [front_left_wheel_spinning_joint,front_right_wheel_spinning_joint]
    steering_joints: [front_left_wheel_steering_joint,front_right_wheel_steering_joint]
    odometry_joints: [front_left_wheel_spinning_joint,front_right_wheel_spinning_joint]
    wheelbase: 1.21

    publish_rate: 50
    pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.3]
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.3]

    odom_frame_id: ipcar/odom
    base_frame_id: ipcar/ipcar_base_footprint
    enable_odom_tf: false

    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_deceleration_limits: true
    max_deceleration: 2.0

/gazebo_ros_control:
  pid_gains:
      front_left_wheel_steering_joint:
          p: 1000.0
          i: 0.01
          d: 10.0

      front_right_wheel_steering_joint:
          p: 1000.0
          i: 0.01
          d: 10.0

direction_controller:
    type: direction_controller/DirectionController
